name: Build Unknown Mod
on:
  push:
    paths:
      - 'unknown.txt'
  workflow_dispatch:

env:
  ver: "v0.2.2 [1.21.11-fabric]"
  tag: "0.2.2-1.21.11"
  java_ver: "25"

jobs:
  build:
    if: ${{ contains(github.event.head_commit.message, '[real]') }}
    permissions:
      contents:
        write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: gradle/actions/wrapper-validation@v6

      - name: setup jdk
        uses: actions/setup-java@v5.3.0
        with:
          java-version: ${{ env.java_ver }}
          distribution: 'temurin'

      - run: chmod +x ./gradlew

      - run: ./gradlew :unknown-mod:build

      - name: capture
        uses: actions/upload-artifact@v7
        with:
          name: jars
          path: unknown-mod/build/libs

  modrinth:
    if: ${{ contains(github.event.head_commit.message, '[mr]') }}

    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: gradle/actions/wrapper-validation@v6

      - name: setup jdk
        uses: actions/setup-java@v5.3.0
        with:
          java-version: ${{ env.java_ver }}
          distribution: 'temurin'

      - name: exe gradlew & publish to modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.TOKEN }}
        run: |
          chmod +x ./gradlew
          ./gradlew :unknown-mod:modrinth

  release:
    permissions:
      contents:
        write

    needs: [ build ]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: download
        uses: actions/download-artifact@v8
        with:
          path: jars
          merge-multiple: true

      - name: create
        uses: softprops/action-gh-release@v3
        with:
          name: Unknown Mod ${{ env.ver }}
          tag_name: ${{ env.tag }}
          body_path: ${{ github.workspace }}/unknown-mod/changelog.md
          draft: true
          generate_release_notes: true
          files: |
            jars/*.jar